version: '3.8'

services:
  backend:
    build:
      context: ./BACKEND      
      dockerfile: Dockerfile
    container_name: face-restore-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/WEIGHTS  
    environment:
      - MAX_UPLOAD_SIZE_BYTES=10485760
      - DEVICE=cpu

  frontend:
    build:
      context: ./FRONTEND     
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://13.217.210.171:8000/api/v1
    container_name: face-restore-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
